server:
  port: 9100
spring:
  application:
    name: users
endpoints:
  shutdown:
    enabled: true
  restart:
    enabled: true
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/